# -*- coding: utf-8 -*-
"""student academic performance_EDA ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_aD_7hZA-XgKKnIBDGxNS2fWzkJOlVl

# **Exploratory Data Analysis on student Academic Performance**

### **Import Libraries**
"""

# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

"""We begin by importing essential Python libraries.
NumPy for numerical operations
Pandas for data manipulation
Seaborn and Matplotlib for statistical and exploratory visualizations
Plotly for interactive charts

### **Load Dataset**
"""

#load dataset
df = pd.read_csv("/content/Final_Marks_Data.csv")
df.head(5)

#last 5 rows of the dataset
df.tail(5)

"""### **Summary Statics**"""

df.shape

"""We load the student performance dataset, which contains 2000 rows and 7 columns.
This dataset includes attendance, internal assessments, study hours, and final exam scores.
"""

df.describe()

"""Key insights from the descriptive statistics:

In student performance dataset the attendance percentage range from 52 % to 100%  and the average is 84%. Internal tests avg ~32/40, showing strong mid-term understanding.
Final exam avg ~65/100, lower than internal tests  indicates final exam is more challenging.
Most students study 2–3 hours/day, which aligns with average performance.
High variation in final scores (25–100) shows differing study habits and skill levels.
"""

#info of dataset
df.info()

"""in student performance dataset there is no mssing value ,and only one column student Id is object and other are numerical.

### **Data Visualization**
"""

sns.heatmap(df.drop("Student_ID", axis = 1).corr(), annot= True, yticklabels = True,  cbar = True, cmap = "viridis")

"""this heatmap shows the correlation between the columns."""

# Custom list of colors
my_colors = ["#9b59b6", "#3498db", "#2ecc71"]
sns.boxplot(x = "Daily Study Hours" , y = "Final Exam Marks (out of 100)", data = df, palette = my_colors)

"""Students studying 3+ hours/day tend to score higher in final exams.

Clear upward trend as study hours increase.
"""

import plotly.express as px
fig = px.histogram(df , x = df['Final Exam Marks (out of 100)'], title = "histogram for marks distribution ")
fig.show()

fig = px.scatter(df, x='Attendance (%)', y='Final Exam Marks (out of 100)',
                 size='Assignment Score (out of 10)', color='Internal Test 1 (out of 40)',
                 hover_data=['Student_ID'],
                 title='Attendance vs Final Marks with Test & Assignment info')
fig.show()

"""Higher attendance generally leads to better exam performance.

Large bubbles (high assignment score) and darker colors (high Test 1 score) cluster at higher exam marks.
"""

fig = px.scatter(df,
                 x= 'Internal Test 1 (out of 40)',
                 y = 'Final Exam Marks (out of 100)',
                 trendline = "ols",
                 title = "Internal Test 1 vs Final Exam Marks"
                 )
fig.show()

"""Strong positive relationship.

Students with higher internal test scores tend to score higher in the final exam.
"""

fig = px.scatter(df,
                 x='Assignment Score (out of 10)',
                 y='Final Exam Marks (out of 100)',
                 trendline='ols',
                 title='Assignment Score vs Final Exam Marks')
fig.show()

"""Assignment performance also positively impacts final exam marks.

Students scoring 8–10 in assignments consistently achieve higher final scores.
"""

fig = px.scatter(df,
                 x='Internal Test 1 (out of 40)',
                 y='Final Exam Marks (out of 100)',
                 size='Assignment Score (out of 10)',
                 color='Internal Test 2 (out of 40)',
                 hover_data=['Student_ID'],
                 title='Combined Impact of Tests & Assignment on Final Exam Marks')
fig.show()

"""Test 2 has slightly higher variability.

Assignment scores are more tightly clustered.
"""

import plotly.express as px

score_df = df[['Internal Test 1 (out of 40)',
               'Internal Test 2 (out of 40)',
               'Assignment Score (out of 10)']]

fig = px.box(score_df,
             title='Distribution Comparison: Test 1, Test 2, Assignment')
fig.show()

"""tudents performed well overall in all three assessments, with medians in the high B to low A range.Test 2 has a slightly higher median compared to Test 1, indicating minor improvement or a slightly easier test.Assignment scores show the least variability, meaning students performed uniformly well."""